export const MODEL_COLORS = {
  'chatgpt': '#10B981',
  'gemini-pro': '#2563EB',
  'gemini-flash': '#60A5FA',
  'copilot': '#0EA5E9',
  'kimi': '#8B5CF6',
  'grok': '#000000',
  'qwen': '#F97316',
  'perplexity': '#20B2AA',
  'firefly': '#FF5A5F',
  'other': '#6B7280',
};

export const MODELS = [
  {
    id: 'gemini-pro',
    name: 'Gemini 3.1 Pro',
    roleTag: 'Vision & Reasoning Leader',
    strength: '2x reasoning jump over 3.0 (ARC-AGI-2: 77.1%). MMMU 92.6%, GPQA Diamond 94.3%. Best-in-class multimodal reasoning with 1M-token context',
    tradeoff: 'Requires Gemini Advanced subscription; heavier and slower than Flash',
    url: 'https://gemini.google.com',
    color: MODEL_COLORS['gemini-pro'],
    benchmark: 'ARC-AGI-2: 77.1%',
  },
  {
    id: 'gemini-flash',
    name: 'Gemini 3 Flash',
    roleTag: 'Free / Fast Vision',
    strength: 'Free-tier vision model with strong scene-level understanding. Massive adoption — most-used model on LM Arena (651K votes)',
    tradeoff: 'Less spatial precision and depth than Pro; misses subtle textures and background details',
    url: 'https://gemini.google.com',
    color: MODEL_COLORS['gemini-flash'],
    benchmark: '—',
  },
  {
    id: 'chatgpt',
    name: 'GPT-5.2',
    roleTag: 'Versatile / Top Tier',
    strength: 'MMMU-Pro: 75%. Excellent at structured visual understanding — charts, diagrams, UI screenshots. o3 mode excels at complex multi-step visual problems',
    tradeoff: 'Persistent weaknesses in spatial reasoning and object counting across multiple generations',
    url: 'https://chatgpt.com',
    color: MODEL_COLORS['chatgpt'],
    benchmark: 'MMMU-Pro: 75%',
  },
  {
    id: 'copilot',
    name: 'MS Copilot',
    roleTag: 'Accessible / Enterprise',
    strength: 'Multimodal out of the box — image upload with typed or voice prompts, no setup. Integrated into Microsoft 365 apps',
    tradeoff: 'Model routing is automatic (GPT under the hood, version not user-controlled). Best vision requires M365 Copilot access',
    url: 'https://copilot.microsoft.com',
    color: MODEL_COLORS['copilot'],
    benchmark: '—',
  },
  {
    id: 'grok',
    name: 'Grok 4.1',
    roleTag: 'Cultural / Contextual',
    strength: 'Strong at social-media visuals, memes, screenshots, and OCR text extraction. Real-time X/Twitter context integration',
    tradeoff: 'Advanced multimodal still in beta. Image generation (Aurora) has documented quality and safety issues',
    url: 'https://grok.com',
    color: MODEL_COLORS['grok'],
    benchmark: '—',
  },
  {
    id: 'kimi',
    name: 'Kimi K2.5',
    roleTag: 'Cross-Modal Reasoning',
    strength: 'Native multimodal with 256K context. Agent Swarm mode (up to 100 parallel sub-agents). Strong CJK and coding benchmarks',
    tradeoff: 'Hallucination rates flagged as high in independent testing (EPFL HalluHard). Agent Swarm still in beta',
    url: 'https://kimi.moonshot.cn',
    color: MODEL_COLORS['kimi'],
    benchmark: '—',
  },
  {
    id: 'qwen',
    name: 'Qwen3.5',
    roleTag: 'Document / OCR Leader',
    strength: 'OmniDocBench: 90.8% — outperforms every proprietary model on document OCR and understanding. Open-source (Apache 2.0)',
    tradeoff: 'Strongest on documents; less tested for creative / artistic image description tasks',
    url: 'https://chat.qwen.ai',
    color: MODEL_COLORS['qwen'],
    benchmark: 'OmniDocBench: 90.8%',
  },
  {
    id: 'perplexity',
    name: 'Perplexity Sonar',
    roleTag: 'Search-Grounded',
    strength: 'Cross-references image content against live web results — useful for identifying real-world objects, products, or places',
    tradeoff: 'Image upload is a Pro-only feature; free tier is text-only',
    url: 'https://www.perplexity.ai',
    color: MODEL_COLORS['perplexity'],
    benchmark: '—',
  },
];

export function getModel(id) {
  return MODELS.find(m => m.id === id);
}
